// fadParity.test.ts — parity checks against franken_agent_detection (FAD).
//
// tests/fixtures/fad/home is a fake HOME laid out in each agent's native
// directory shape; tests/fixtures/fad/expected/*.fad.json are generated by
// `bun run scripts/regen-fad-fixtures.ts`, which runs the dev-only
// tools/fad-dump Rust shim over the same tree.
//
// Assertions, per FAD-discovered conversation:
//   1. agentboard discovers/parses the same source file
//   2. agent type, project path, and session id agree (FAD's external_id is
//      path-derived for file agents, so id parity accepts metadata fields)
//   3. every user message agentboard extracts is contained in FAD's
//      role:"user" set (agentboard may legitimately drop more — isMeta,
//      tool notifications, devin keepalives — but may never invent one)
//
// Regenerate after changing fixtures: bun run scripts/regen-fad-fixtures.ts

import { describe, expect, test, beforeAll, afterAll } from 'bun:test'
import { Database } from 'bun:sqlite'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {
  extractProjectPath,
  extractSessionId,
  inferAgentTypeFromPath,
  normalizeProjectPath,
} from '../logDiscovery'
import { normalizeAgentLogEntry } from '../../shared/eventTaxonomy'
import { syncDevinSessions } from '../devinSync'
import type { AgentType } from '../../shared/types'

const FAD_DIR = path.resolve(import.meta.dir, '..', '..', '..', 'tests', 'fixtures', 'fad')
const FAD_HOME = path.join(FAD_DIR, 'home')
const EXPECTED_DIR = path.join(FAD_DIR, 'expected')
const SEED_SQL = path.join(FAD_DIR, 'seeds', 'devin.sql')

// FAD factory slug -> agentboard AgentType
const AGENT_MAP: Record<string, AgentType> = {
  claude: 'claude',
  codex: 'codex',
  pi_agent: 'pi',
  omp: 'omp',
  grok: 'grok',
  devin: 'devin',
}

interface FadMessage {
  idx: number
  role: string
  content: string
  createdAt: number | null
}

interface FadConversation {
  agent: string
  externalId: string | null
  title: string | null
  workspace: string | null
  sourcePath: string
  startedAt: number | null
  endedAt: number | null
  metadata?: Record<string, unknown>
  messages: FadMessage[]
}

const ENV_KEYS = [
  'CLAUDE_CONFIG_DIR',
  'CODEX_HOME',
  'PI_HOME',
  'GROK_HOME',
  'PI_CODING_AGENT_DIR',
  'AGENTBOARD_DATA_DIR',
  'DEVIN_CLI_DIR',
] as const
const savedEnv: Record<string, string | undefined> = {}

let tempRoot: string

beforeAll(() => {
  for (const key of ENV_KEYS) savedEnv[key] = process.env[key]
  tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agentboard-fad-parity-'))
  process.env.CLAUDE_CONFIG_DIR = path.join(FAD_HOME, '.claude')
  process.env.CODEX_HOME = path.join(FAD_HOME, '.codex')
  process.env.PI_HOME = path.join(FAD_HOME, '.pi')
  process.env.GROK_HOME = path.join(FAD_HOME, '.grok')
  process.env.PI_CODING_AGENT_DIR = path.join(FAD_HOME, '.omp', 'agent')
  process.env.AGENTBOARD_DATA_DIR = path.join(tempRoot, 'agentboard')
})

afterAll(() => {
  for (const key of ENV_KEYS) {
    if (savedEnv[key] === undefined) delete process.env[key]
    else process.env[key] = savedEnv[key]
  }
  fs.rmSync(tempRoot, { recursive: true, force: true })
})

function collapseWhitespace(text: string): string {
  return text.replace(/\s+/g, ' ').trim()
}

/** User-visible message texts agentboard extracts from a JSONL log file. */
function agentboardUserTexts(logPath: string): string[] {
  const out: string[] = []
  for (const line of fs.readFileSync(logPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed) continue
    let entry: unknown
    try {
      entry = JSON.parse(trimmed)
    } catch {
      continue
    }
    for (const event of normalizeAgentLogEntry(entry)) {
      if (event.kind === 'message' && event.role === 'user' && event.text) {
        out.push(collapseWhitespace(event.text))
      }
    }
  }
  return out
}

function fadUserTexts(conv: FadConversation): string[] {
  return conv.messages
    .filter((m) => m.role === 'user')
    .map((m) => collapseWhitespace(m.content))
}

/**
 * FAD's sourcePath is real for file-backed agents; for multi-conversation
 * stores (devin's sessions.db) it is virtual: <db>/<session-id>. Walk up to
 * the first path that exists on disk.
 */
function realSourcePath(sourcePath: string): string {
  let p = sourcePath
  while (!fs.existsSync(p) && p !== path.dirname(p)) {
    p = path.dirname(p)
  }
  return p
}

function expectUserSubset(conv: FadConversation, ours: string[], context: string) {
  const theirs = fadUserTexts(conv)
  for (const text of ours) {
    const found = theirs.some((fad) => fad.includes(text))
    expect(
      found,
      `${context}: agentboard user message not in FAD user messages: ${JSON.stringify(text.slice(0, 120))}`
    ).toBe(true)
  }
}

function expectSessionIdParity(conv: FadConversation, sid: string | null, context: string) {
  expect(sid, `${context}: agentboard extracted no session id`).toBeTruthy()
  const metadata = JSON.stringify(conv.metadata ?? {})
  const known =
    conv.externalId === sid ||
    conv.externalId?.includes(sid!) === true ||
    metadata.includes(sid!)
  expect(
    known,
    `${context}: session id ${sid} not found in FAD externalId/metadata`
  ).toBe(true)
}

function expectedFiles(): string[] {
  if (!fs.existsSync(EXPECTED_DIR)) return []
  return fs.readdirSync(EXPECTED_DIR).filter((f) => f.endsWith('.fad.json'))
}

const files = expectedFiles()

describe('FAD parity', () => {
  test('expected fixtures exist (run scripts/regen-fad-fixtures.ts)', () => {
    expect(files.length).toBeGreaterThan(0)
  })

  for (const name of files) {
    const conv = JSON.parse(
      fs.readFileSync(path.join(EXPECTED_DIR, name), 'utf8')
    ) as FadConversation
    if (conv.agent === 'devin') continue // devin is exercised via devinSync below

    test(`${name}`, () => {
      const logPath = realSourcePath(conv.sourcePath)
      expect(fs.existsSync(logPath)).toBe(true)

      expect(inferAgentTypeFromPath(logPath)).toBe(AGENT_MAP[conv.agent])
      expectSessionIdParity(conv, extractSessionId(logPath), name)
      expect(extractProjectPath(logPath)).toBe(
        normalizeProjectPath(conv.workspace ?? '')
      )
      expectUserSubset(conv, agentboardUserTexts(logPath), name)
    })
  }

  test('devin: devinSync mirror agrees with FAD on sessions.db', () => {
    const devinExpected = files.find((f) => f.startsWith('devin__'))
    expect(devinExpected).toBeTruthy()
    const conv = JSON.parse(
      fs.readFileSync(path.join(EXPECTED_DIR, devinExpected!), 'utf8')
    ) as FadConversation

    // Rebuild the fixture db in tmp and point devinSync at it.
    const devinCliDir = path.join(tempRoot, 'devin-cli')
    fs.mkdirSync(devinCliDir, { recursive: true })
    const dbPath = path.join(devinCliDir, 'sessions.db')
    const db = new Database(dbPath)
    try {
      db.exec(fs.readFileSync(SEED_SQL, 'utf8'))
    } finally {
      db.close()
    }
    process.env.DEVIN_CLI_DIR = devinCliDir

    const outDir = path.join(process.env.AGENTBOARD_DATA_DIR!, 'devin-sessions')
    const result = syncDevinSessions(outDir)
    expect(result).not.toBeNull()

    const mirrorPath = path.join(outDir, `${conv.externalId}.jsonl`)
    expect(fs.existsSync(mirrorPath)).toBe(true)

    expect(inferAgentTypeFromPath(mirrorPath)).toBe('devin')
    expectSessionIdParity(conv, extractSessionId(mirrorPath), 'devin')
    expect(extractProjectPath(mirrorPath)).toBe(
      normalizeProjectPath(conv.workspace ?? '')
    )
    expectUserSubset(conv, agentboardUserTexts(mirrorPath), 'devin')
  })
})
